/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.xavier.csci;

public class App {
    public String getGreeting() {
        GreetingUtil g = new GreetingUtil();
        return g.getGreeting("InClass");
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
